import type { Category, Ingredient, RecipeStep, RecipeTag, RecipeTagging, StatusOption } from './types.js'

export interface SeedRecipe {
  id: number
  name: string
  coverKey: string
  heroKey: string
  thumbnailKey: string
  categoryId: string
  categoryIds?: string[]
  category: string
  tags: string[]
  statusIds: string[]
  taggings?: RecipeTagging[]
  reason: string
  cookTime: number
  calories: number
  popularity: number
  servings: number
  difficulty: '简单' | '适中' | '进阶'
  ingredients: Ingredient[]
  steps: Array<Omit<RecipeStep, 'image'> & { imageKey: string }>
  sortOrder: number
}

export const categorySeeds: Category[] = [
  { id: 'cook', source: 'quick', name: '自己做', description: '营养又安心', icon: '/static/images/home/action-cook.png' },
  { id: 'takeout', source: 'quick', name: '点外卖', description: '省时又方便', icon: '/static/images/home/action-takeout.png' },
  { id: 'recover', source: 'quick', name: '恢复期', description: '科学助恢复', icon: '/static/images/home/action-recover.png' },
  { id: 'quick', source: 'cooking', name: '快手菜', description: '15分钟上桌', icon: '/static/images/category/cooking/quick-icon.png', cover: 'images/category/cooking/quick-cover.jpg' },
  { id: 'home-style', source: 'cooking', name: '家常菜', description: '家的味道', icon: '/static/images/category/cooking/home-style-icon.png', cover: 'images/category/cooking/home-style-cover.jpg' },
  { id: 'soup', source: 'cooking', name: '汤羹', description: '温暖滋养', icon: '/static/images/category/cooking/soup-icon.png', cover: 'images/category/cooking/soup-cover.jpg' },
  { id: 'light', source: 'cooking', name: '清淡', description: '少油少盐', icon: '/static/images/category/cooking/light-icon.png', cover: 'images/category/cooking/light-cover.jpg' },
  { id: 'recovery', source: 'cooking', name: '恢复期', description: '营养修复', icon: '/static/images/category/cooking/recovery-icon.png', cover: 'images/category/cooking/recovery-cover.jpg' },
  { id: 'hot-pot', source: 'takeout', name: '火锅', description: '热辣过瘾', icon: '/static/images/category/takeout/hot-pot-icon.png', cover: 'images/category/takeout/hot-pot-cover.jpg' },
  { id: 'noodles', source: 'takeout', name: '面食', description: '面面俱到', icon: '/static/images/category/takeout/noodles-icon.png', cover: 'images/category/takeout/noodles-cover.jpg' },
  { id: 'light-meal', source: 'takeout', name: '轻食', description: '轻盈健康', icon: '/static/images/category/takeout/light-meal-icon.png', cover: 'images/category/takeout/light-meal-cover.jpg' },
  { id: 'fried-chicken', source: 'takeout', name: '炸鸡', description: '酥脆满足', icon: '/static/images/category/takeout/fried-chicken-icon.png', cover: 'images/category/takeout/fried-chicken-cover.jpg' },
  { id: 'japanese', source: 'takeout', name: '日料', description: '新鲜美味', icon: '/static/images/category/takeout/japanese-icon.png', cover: 'images/category/takeout/japanese-cover.jpg' },
]

export const statusSeeds: StatusOption[] = [
  { id: 'recover', name: '骨折恢复期', icon: '🦴' },
  { id: 'fitness', name: '健身期', icon: '💪' },
  { id: 'late', name: '熬夜', icon: '🌙' },
  { id: 'rainy', name: '下雨天', icon: '🌧️' },
  { id: 'lazy', name: '犯懒', icon: '😴' },
  { id: 'appetite', name: '没胃口', icon: '😟' },
  { id: 'cold', name: '感冒发烧', icon: '🤒' },
  { id: 'stress', name: '压力很大', icon: '😣' },
  { id: 'light', name: '清淡饮食', icon: '🥬' },
  { id: 'energy', name: '需要补能', icon: '⚡' },
  { id: 'normal', name: '状态不错', icon: '😊' },
]

interface SimpleRecipeSeed {
  id: number
  name: string
  imageKey: string
  categoryId: string
  categoryIds?: string[]
  category: string
  tags: string[]
  statusIds: string[]
  reason: string
  cookTime: number
  calories: number
  popularity: number
  servings?: number
  difficulty?: SeedRecipe['difficulty']
  ingredients: Ingredient[]
  sortOrder: number
}

function simpleRecipe(seed: SimpleRecipeSeed): SeedRecipe {
  const { imageKey, ...recipe } = seed
  return {
    ...recipe,
    coverKey: imageKey,
    heroKey: imageKey,
    thumbnailKey: imageKey,
    servings: seed.servings ?? 2,
    difficulty: seed.difficulty ?? '简单',
    steps: [{ text: `备好食材，按家常做法完成${seed.name}，少油少盐调味。`, imageKey }],
  }
}

export const recipeSeeds: SeedRecipe[] = [
  {
    id: 1001,
    name: '山药排骨汤',
    coverKey: 'images/recipes/yam-pork-rib-soup-card.jpg',
    heroKey: 'images/recipes/yam-pork-rib-soup-hero.jpg',
    thumbnailKey: 'images/recipes/yam-pork-rib-soup-thumb.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'recovery'],
    category: '汤羹',
    tags: ['高钙', '低脂', '易消化'],
    statusIds: ['recover', 'appetite', 'rainy'],
    reason: '富含钙与胶原蛋白，温润清淡，适合恢复期补充营养。',
    cookTime: 40,
    calories: 320,
    popularity: 9386,
    servings: 2,
    difficulty: '简单',
    ingredients: [
      { name: '猪排骨', amount: '500g', icon: '🥩' },
      { name: '山药', amount: '300g', icon: '🥔' },
      { name: '红枣', amount: '5 颗', icon: '🔴' },
      { name: '姜片', amount: '3 片', icon: '🫚' },
      { name: '枸杞', amount: '1 小把', icon: '🫐' },
      { name: '盐', amount: '适量', icon: '🧂' },
      { name: '清水', amount: '适量', icon: '💧' },
    ],
    steps: [
      { text: '排骨切块，冷水下锅焯水，去除血沫，捞出沥干。', imageKey: 'images/category/cooking/home-style-cover.jpg' },
      { text: '山药去皮切块，红枣洗净，姜切片备用。', imageKey: 'images/plan/meals/tomato-beef-congee.jpg' },
      { text: '锅中加清水，放入排骨和姜片炖煮，加入山药调味。', imageKey: 'images/recipes/yam-pork-rib-soup-thumb.jpg' },
    ],
    sortOrder: 10,
  },
  {
    id: 1002,
    name: '番茄牛腩',
    coverKey: 'images/category/cooking/home-style-cover.jpg',
    heroKey: 'images/category/cooking/home-style-cover.jpg',
    thumbnailKey: 'images/category/cooking/home-style-cover.jpg',
    categoryId: 'home-style',
    categoryIds: ['home-style', 'soup'],
    category: '家常菜',
    tags: ['高蛋白', '补铁', '强健体能'],
    statusIds: ['fitness', 'energy', 'normal'],
    taggings: [
      { tagId: 'fitness', weight: 120, source: 'manual', confidence: 1 },
      { tagId: 'energy', weight: 105, source: 'manual', confidence: 1 },
      { tagId: 'normal', weight: 85, source: 'manual', confidence: 1 },
    ],
    reason: '牛腩提供优质蛋白和铁，番茄清爽解腻，适合健身期补充能量。',
    cookTime: 35,
    calories: 280,
    popularity: 8724,
    servings: 2,
    difficulty: '简单',
    ingredients: [
      { name: '牛腩', amount: '300g', icon: '🥩' },
      { name: '番茄', amount: '2 个', icon: '🍅' },
      { name: '洋葱', amount: '半个', icon: '🧅' },
      { name: '姜片', amount: '3 片', icon: '🫚' },
      { name: '盐', amount: '适量', icon: '🧂' },
      { name: '食用油', amount: '适量', icon: '🫗' },
      { name: '清水', amount: '适量', icon: '💧' },
    ],
    steps: [
      { text: '牛肉切块，冷水下锅焯水，去除血沫后捞出。', imageKey: 'images/category/cooking/home-style-cover.jpg' },
      { text: '番茄切块，洋葱切丝，姜切片备用。', imageKey: 'images/plan/meals/tomato-beef-congee.jpg' },
      { text: '锅中热油炒香配料，加水炖煮至牛肉软烂。', imageKey: 'images/category/cooking/home-style-cover.jpg' },
    ],
    sortOrder: 20,
  },
  {
    id: 1003,
    name: '西兰花炒虾仁',
    coverKey: 'images/category/cooking/light-cover.jpg',
    heroKey: 'images/category/cooking/light-cover.jpg',
    thumbnailKey: 'images/category/cooking/light-cover.jpg',
    categoryId: 'light',
    categoryIds: ['light', 'quick'],
    category: '清淡快手菜',
    tags: ['清淡', '低脂', '高蛋白'],
    statusIds: ['fitness', 'late', 'lazy', 'appetite'],
    reason: '虾仁鲜嫩高蛋白，搭配西兰花清爽少油，营养均衡。',
    cookTime: 20,
    calories: 220,
    popularity: 8163,
    servings: 2,
    difficulty: '简单',
    ingredients: [
      { name: '鲜虾仁', amount: '250g', icon: '🦐' },
      { name: '西兰花', amount: '300g', icon: '🥦' },
      { name: '蒜瓣', amount: '2 瓣', icon: '🧄' },
      { name: '料酒', amount: '1 勺', icon: '🥄' },
      { name: '盐', amount: '适量', icon: '🧂' },
      { name: '食用油', amount: '适量', icon: '🫗' },
    ],
    steps: [
      { text: '虾仁洗净，用少量料酒和盐腌制十分钟。', imageKey: 'images/category/cooking/light-cover.jpg' },
      { text: '西兰花切小朵焯水，蒜瓣切末备用。', imageKey: 'images/category/cooking/light-cover.jpg' },
      { text: '热锅少油炒香蒜末，放入虾仁和西兰花翻炒。', imageKey: 'images/category/cooking/light-cover.jpg' },
    ],
    sortOrder: 30,
  },
  {
    id: 2001,
    name: '妈妈的红烧肉',
    coverKey: 'images/category/takeout/hot-pot-cover.jpg',
    heroKey: 'images/category/takeout/hot-pot-cover.jpg',
    thumbnailKey: 'images/category/takeout/hot-pot-cover.jpg',
    categoryId: 'home-style',
    category: '家常菜',
    tags: ['家常', '下饭', '经典'],
    statusIds: ['lazy'],
    reason: '软糯入味，经典下饭菜，是记忆中的家的味道。',
    cookTime: 60,
    calories: 520,
    popularity: 7651,
    servings: 2,
    difficulty: '适中',
    ingredients: [{ name: '五花肉', amount: '500g', icon: '🥩' }, { name: '冰糖', amount: '30g', icon: '🧊' }],
    steps: [{ text: '五花肉切块焯水，炒糖色后小火炖至软糯。', imageKey: 'images/category/takeout/hot-pot-cover.jpg' }],
    sortOrder: 40,
  },
  {
    id: 2002,
    name: '玉米排骨汤',
    coverKey: 'images/category/cooking/home-style-cover.jpg',
    heroKey: 'images/category/cooking/home-style-cover.jpg',
    thumbnailKey: 'images/category/cooking/home-style-cover.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'recovery'],
    category: '滋补汤羹',
    tags: ['高钙', '优质蛋白', '温和滋补'],
    statusIds: ['recover', 'appetite', 'rainy'],
    taggings: [
      { tagId: 'recover', weight: 125, source: 'manual', confidence: 1 },
      { tagId: 'appetite', weight: 85, source: 'manual', confidence: 1 },
      { tagId: 'rainy', weight: 80, source: 'manual', confidence: 1 },
    ],
    reason: '玉米清甜、排骨补充蛋白质与钙，口味温和，适合骨折恢复期。',
    cookTime: 40,
    calories: 280,
    popularity: 7028,
    servings: 2,
    difficulty: '简单',
    ingredients: [{ name: '猪排骨', amount: '500g', icon: '🥩' }, { name: '甜玉米', amount: '1 根', icon: '🌽' }],
    steps: [{ text: '排骨焯水，与玉米一起小火炖至汤清肉软。', imageKey: 'images/category/cooking/soup-cover.jpg' }],
    sortOrder: 50,
  },
  {
    id: 2003,
    name: '青椒炒牛肉',
    coverKey: 'images/category/cooking/quick-cover.jpg',
    heroKey: 'images/category/cooking/quick-cover.jpg',
    thumbnailKey: 'images/category/cooking/quick-cover.jpg',
    categoryId: 'quick',
    category: '快手菜',
    tags: ['快手', '高蛋白', '下饭'],
    statusIds: ['late', 'lazy'],
    reason: '牛肉鲜嫩、青椒爽脆，简单快手又适合日常搭配。',
    cookTime: 20,
    calories: 360,
    popularity: 6894,
    servings: 2,
    difficulty: '简单',
    ingredients: [{ name: '牛肉', amount: '250g', icon: '🥩' }, { name: '青椒', amount: '2 个', icon: '🫑' }],
    steps: [{ text: '牛肉腌制后大火滑炒，再加入青椒快速翻炒。', imageKey: 'images/category/cooking/quick-cover.jpg' }],
    sortOrder: 60,
  },
  simpleRecipe({
    id: 2004,
    name: '清蒸鲈鱼',
    imageKey: 'images/plan/meals/steamed-fish.jpg',
    categoryId: 'light',
    categoryIds: ['light', 'recovery'],
    category: '清淡菜',
    tags: ['高蛋白', '低脂', '易消化'],
    statusIds: ['recover', 'fitness', 'light'],
    reason: '鲈鱼高蛋白、脂肪适中，清蒸做法清淡，适合恢复期和健身期。',
    cookTime: 25,
    calories: 210,
    popularity: 8520,
    ingredients: [{ name: '鲈鱼', amount: '1 条', icon: '🐟' }, { name: '姜葱', amount: '适量', icon: '🫚' }],
    sortOrder: 70,
  }),
  simpleRecipe({
    id: 2005,
    name: '香菇蒸鸡',
    imageKey: 'images/category/cooking/recovery-cover.jpg',
    categoryId: 'home-style',
    categoryIds: ['home-style', 'recovery'],
    category: '家常菜',
    tags: ['高蛋白', '少油', '鲜香'],
    statusIds: ['recover', 'fitness', 'energy'],
    reason: '鸡肉提供优质蛋白，蒸制少油，香菇增加鲜味，营养又温和。',
    cookTime: 35,
    calories: 330,
    popularity: 8310,
    ingredients: [{ name: '鸡腿肉', amount: '350g', icon: '🍗' }, { name: '香菇', amount: '6 朵', icon: '🍄' }],
    sortOrder: 80,
  }),
  simpleRecipe({
    id: 2006,
    name: '番茄炒蛋',
    imageKey: 'images/category/cooking/quick-cover.jpg',
    categoryId: 'quick',
    categoryIds: ['quick', 'home-style'],
    category: '快手菜',
    tags: ['快手', '开胃', '家常'],
    statusIds: ['lazy', 'appetite', 'normal'],
    reason: '酸甜开胃、十几分钟就能完成，是忙碌或没胃口时的稳妥选择。',
    cookTime: 15,
    calories: 260,
    popularity: 9600,
    ingredients: [{ name: '番茄', amount: '2 个', icon: '🍅' }, { name: '鸡蛋', amount: '3 个', icon: '🥚' }],
    sortOrder: 90,
  }),
  simpleRecipe({
    id: 2007,
    name: '冬瓜虾皮汤',
    imageKey: 'images/category/cooking/soup-cover.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'light'],
    category: '清淡汤羹',
    tags: ['清淡', '低脂', '补钙'],
    statusIds: ['recover', 'light', 'appetite'],
    reason: '汤味清鲜、负担较轻，虾皮还能补充钙质。',
    cookTime: 20,
    calories: 120,
    popularity: 7440,
    ingredients: [{ name: '冬瓜', amount: '400g', icon: '🥒' }, { name: '虾皮', amount: '20g', icon: '🦐' }],
    sortOrder: 100,
  }),
  simpleRecipe({
    id: 2008,
    name: '芹菜炒鸡胸肉',
    imageKey: 'images/category/cooking/light-cover.jpg',
    categoryId: 'light',
    categoryIds: ['light', 'quick'],
    category: '低脂快手菜',
    tags: ['高蛋白', '低脂', '高纤维'],
    statusIds: ['fitness', 'light', 'normal'],
    reason: '鸡胸肉补充蛋白质，芹菜增加纤维，适合健身期的日常正餐。',
    cookTime: 20,
    calories: 240,
    popularity: 8050,
    ingredients: [{ name: '鸡胸肉', amount: '250g', icon: '🍗' }, { name: '芹菜', amount: '250g', icon: '🥬' }],
    sortOrder: 110,
  }),
  simpleRecipe({
    id: 2009,
    name: '南瓜小米粥',
    imageKey: 'images/plan/meals/tomato-beef-congee.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'light'],
    category: '粥品',
    tags: ['暖胃', '易消化', '清淡'],
    statusIds: ['late', 'appetite', 'rainy'],
    reason: '软糯温热、容易消化，熬夜后或胃口不佳时更容易入口。',
    cookTime: 35,
    calories: 190,
    popularity: 7790,
    ingredients: [{ name: '南瓜', amount: '250g', icon: '🎃' }, { name: '小米', amount: '80g', icon: '🌾' }],
    sortOrder: 120,
  }),
  simpleRecipe({
    id: 2010,
    name: '菠菜猪肝汤',
    imageKey: 'images/category/cooking/soup-cover.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'recovery'],
    category: '营养汤羹',
    tags: ['补铁', '补能量', '家常'],
    statusIds: ['energy', 'recover'],
    reason: '猪肝和菠菜富含铁，适合需要补充能量时作为多样化饮食的一部分。',
    cookTime: 25,
    calories: 230,
    popularity: 6900,
    ingredients: [{ name: '猪肝', amount: '200g', icon: '🥩' }, { name: '菠菜', amount: '200g', icon: '🥬' }],
    sortOrder: 130,
  }),
  simpleRecipe({
    id: 2011,
    name: '鲜虾蒸蛋',
    imageKey: 'images/plan/meals/steamed-egg.jpg',
    categoryId: 'light',
    categoryIds: ['light', 'recovery'],
    category: '清淡菜',
    tags: ['高蛋白', '嫩滑', '易消化'],
    statusIds: ['recover', 'appetite', 'light'],
    reason: '鸡蛋嫩滑、虾仁鲜甜，口感温和，适合恢复期或没胃口时。',
    cookTime: 18,
    calories: 200,
    popularity: 8890,
    ingredients: [{ name: '鸡蛋', amount: '2 个', icon: '🥚' }, { name: '虾仁', amount: '80g', icon: '🦐' }],
    sortOrder: 140,
  }),
  simpleRecipe({
    id: 2012,
    name: '蒜蓉时蔬',
    imageKey: 'images/category/cooking/light-cover.jpg',
    categoryId: 'light',
    categoryIds: ['light', 'quick'],
    category: '清淡快手菜',
    tags: ['高纤维', '低脂', '快手'],
    statusIds: ['light', 'lazy', 'normal'],
    reason: '当季蔬菜简单快炒，补充膳食纤维，也方便搭配其他主菜。',
    cookTime: 12,
    calories: 130,
    popularity: 7200,
    ingredients: [{ name: '当季蔬菜', amount: '400g', icon: '🥬' }, { name: '蒜瓣', amount: '3 瓣', icon: '🧄' }],
    sortOrder: 150,
  }),
  simpleRecipe({
    id: 2013,
    name: '糙米鸡肉饭',
    imageKey: 'images/plan/meals/brown-rice.jpg',
    categoryId: 'home-style',
    categoryIds: ['home-style', 'light'],
    category: '营养主食',
    tags: ['高蛋白', '粗粮', '饱腹'],
    statusIds: ['fitness', 'energy', 'normal'],
    reason: '糙米提供复合碳水，鸡肉补充蛋白质，适合训练日均衡补能。',
    cookTime: 35,
    calories: 480,
    popularity: 8420,
    ingredients: [{ name: '糙米', amount: '120g', icon: '🍚' }, { name: '鸡腿肉', amount: '220g', icon: '🍗' }],
    sortOrder: 160,
  }),
  simpleRecipe({
    id: 2014,
    name: '菌菇豆腐汤',
    imageKey: 'images/category/cooking/soup-cover.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'light'],
    category: '清淡汤羹',
    tags: ['植物蛋白', '清淡', '暖胃'],
    statusIds: ['light', 'rainy', 'late'],
    reason: '菌菇鲜香、豆腐柔嫩，清淡暖胃又不会过分油腻。',
    cookTime: 22,
    calories: 170,
    popularity: 7680,
    ingredients: [{ name: '嫩豆腐', amount: '300g', icon: '⬜' }, { name: '混合菌菇', amount: '200g', icon: '🍄' }],
    sortOrder: 170,
  }),
  simpleRecipe({
    id: 2015,
    name: '牛奶燕麦杯',
    imageKey: 'images/plan/meals/milk.jpg',
    categoryId: 'quick',
    categoryIds: ['quick', 'light'],
    category: '快手早餐',
    tags: ['高钙', '粗粮', '快手'],
    statusIds: ['fitness', 'energy', 'lazy'],
    reason: '牛奶搭配燕麦，准备简单，能同时补充钙和稳定碳水。',
    cookTime: 8,
    calories: 280,
    popularity: 8120,
    servings: 1,
    ingredients: [{ name: '牛奶', amount: '250ml', icon: '🥛' }, { name: '燕麦片', amount: '50g', icon: '🌾' }],
    sortOrder: 180,
  }),
  simpleRecipe({
    id: 2016,
    name: '水果酸奶碗',
    imageKey: 'images/plan/meals/fruit-platter.jpg',
    categoryId: 'quick',
    categoryIds: ['quick', 'light'],
    category: '快手加餐',
    tags: ['高纤维', '清爽', '快手'],
    statusIds: ['fitness', 'appetite', 'normal'],
    reason: '水果和酸奶清爽易入口，适合作为训练后或午后的简单加餐。',
    cookTime: 8,
    calories: 230,
    popularity: 8350,
    servings: 1,
    ingredients: [{ name: '原味酸奶', amount: '200g', icon: '🥛' }, { name: '混合水果', amount: '200g', icon: '🍎' }],
    sortOrder: 190,
  }),
  simpleRecipe({
    id: 2017,
    name: '核桃黑芝麻糊',
    imageKey: 'images/plan/meals/walnuts.jpg',
    categoryId: 'soup',
    categoryIds: ['soup', 'quick'],
    category: '营养加餐',
    tags: ['坚果', '暖胃', '补能量'],
    statusIds: ['energy', 'late', 'rainy'],
    reason: '坚果和芝麻香浓温热，适合天气凉或需要补充能量时少量食用。',
    cookTime: 12,
    calories: 260,
    popularity: 7010,
    servings: 1,
    ingredients: [{ name: '核桃', amount: '20g', icon: '🌰' }, { name: '黑芝麻粉', amount: '35g', icon: '⚫' }],
    sortOrder: 200,
  }),
  simpleRecipe({
    id: 2018,
    name: '肉末茄子',
    imageKey: 'images/category/cooking/home-style-cover.jpg',
    categoryId: 'home-style',
    categoryIds: ['home-style', 'quick'],
    category: '家常菜',
    tags: ['下饭', '家常', '快手'],
    statusIds: ['normal', 'lazy'],
    reason: '软糯下饭、做法家常，适合想吃点有滋味又不想折腾的时候。',
    cookTime: 25,
    calories: 360,
    popularity: 8230,
    ingredients: [{ name: '茄子', amount: '2 根', icon: '🍆' }, { name: '猪肉末', amount: '150g', icon: '🥩' }],
    sortOrder: 210,
  }),
  simpleRecipe({
    id: 2019,
    name: '柠檬香煎鸡腿',
    imageKey: 'images/category/cooking/quick-cover.jpg',
    categoryId: 'quick',
    categoryIds: ['quick', 'home-style'],
    category: '快手菜',
    tags: ['高蛋白', '开胃', '香煎'],
    statusIds: ['fitness', 'appetite', 'normal'],
    reason: '鸡腿肉蛋白质充足，柠檬香气清新，训练期也能吃得有滋味。',
    cookTime: 28,
    calories: 350,
    popularity: 8480,
    ingredients: [{ name: '去皮鸡腿', amount: '2 只', icon: '🍗' }, { name: '柠檬', amount: '半个', icon: '🍋' }],
    sortOrder: 220,
  }),
]

export const recipeTagSeeds: RecipeTag[] = [
  ...statusSeeds.map(status => ({ id: status.id, name: status.name, type: 'status' as const })),
  ...[...new Set(recipeSeeds.flatMap(recipe => recipe.tags))]
    .map(name => ({ id: `feature:${name}`, name, type: 'feature' as const })),
]

export function getSeedTaggings(seed: SeedRecipe): RecipeTagging[] {
  const explicit = new Map(seed.taggings?.map(tagging => [tagging.tagId, tagging]))
  return [
    ...seed.statusIds.map(tagId => explicit.get(tagId) ?? {
      tagId,
      weight: 100,
      source: 'manual' as const,
      confidence: 1,
    }),
    ...seed.tags.map(name => ({
      tagId: `feature:${name}`,
      weight: 100,
      source: 'manual' as const,
      confidence: 1,
    })),
  ]
}
